capture whole filename including dirs and add parsing tests
joehand/hyperdrive-http pull request #13
Opened 2016-09-22 19:18 UTC by joehand

It seems like we weren't capturing the subdirectories before (and they weren't in the tests). 

I added some basic parsing tests for GET requests too. We can extend those now pretty easily for other edge cases.

2016-09-23 08:39 UTC, juliangruber commented on index.js
> +      encoding.encode(Buffer.from(key, 'hex'))
isn't this what `dat-encoding` is already doing? https://github.com/juliangruber/dat-encoding/blob/master/index.js#L12

2016-09-23 08:40 UTC, juliangruber commented on index.js
> +    // console.error(status)
can we remove this line all together then?

2016-09-23 08:41 UTC, juliangruber commented on test/misc.js
> +})
👍

2016-09-23 08:41 UTC, juliangruber requested changes

2016-09-23 15:13 UTC, joehand commented on index.js
> +      encoding.encode(Buffer.from(key, 'hex'))
I thought so, but its not checking if its the right length. This is just a hacky way to make sure its a Dat key (if there is no key then key = filename). 

You think there is a better way to see if that first segment is a key or file?

2016-09-23 15:14 UTC, joehand commented on index.js
> +    // console.error(status)
Oh ya this was a placeholder. We can remove it, any idea of better errors besides just giving a 404? Not sure if this is something we want to show the user though.

2016-09-23 17:01 UTC, joehand commented on index.js
> +      encoding.encode(Buffer.from(key, 'hex'))
We could just do key.length === 64.

2016-09-23 17:02 UTC, joehand commented on index.js
> +    // console.error(status)
Removed. I'll add debug in another PR.

2016-09-24 12:25 UTC, juliangruber commented on index.js
> +      encoding.encode(Buffer.from(key, 'hex'))
`dat-encoding@3.0.1` will now throw on invalid key lenghts. I thought I had a test for this but my test key was `"too short"` which obviously isn't valid hex either, so now I test for both.

2016-11-04 00:39 UTC, joehand commented
omg that took me forever. 🚢

2016-11-04 00:39 UTC, merged